#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Lets check if the code is well formatted 😎'

yarn check-format || (
  echo 'oops! your format doesnt looks good. Run yarn format and try commiting again!';
  false;
)

echo 'Ok, the format looks good, how about lint check? 😋'

yarn check-lint || (
  echo 'oops! you did not meet the linting standards!';
  false;
)

echo 'Awesome, you passed all the checks 😍🎉'